ResponseTimeoutMs: 100
ValidationExcludeRequestBody: false
ValidationExcludeRequestQueryParams: false
ValidationExcludeResponseBody: false
ValidationExcludeReadOnlyValidations: false
ValidationExcludeWriteOnlyValidations: false
ValidationIncludeResponseStatus: false
AuthStore:
  Type: in-memory
  InMemory:
    Salt: change-me
    Data:
      Author 1: Author 1
      Author 2: Author 2
      Author 3: Author 3
Authenticator:
  Type: basic
